server {
    listen 80;
    server_name _;
    return 301 https://$host$request_uri;
}
server {
    listen 443 ssl http2;
    server_name _;
    ssl_certificate /etc/nginx/ssl/server.crt;
    ssl_certificate_key /etc/nginx/ssl/server.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /auth/v1/ {
        proxy_pass http://app_kong:8000/auth/v1/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /rest/v1/ {
        proxy_pass http://app_kong:8000/rest/v1/;
        proxy_set_header apikey "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlzcyI6InN1cGFiYXNlIiwiaWF0IjoxNzc5MjcxMzY4LCJleHAiOjIwOTQ4NDczNjh9.QTifbclu1w8ghuhEyKh6FJQxST03Xt0YgYzF_PeH0zI";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /functions/v1/ {
        proxy_pass http://app_functions:9999/;
        proxy_set_header apikey "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlzcyI6InN1cGFiYXNlIiwiaWF0IjoxNzc5MjcxMzY4LCJleHAiOjIwOTQ4NDczNjh9.QTifbclu1w8ghuhEyKh6FJQxST03Xt0YgYzF_PeH0zI";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
